// The exercise library.
//
// `setup` is the most important field here. The observed bottleneck is not
// motivation or effort — it is standing in front of a machine unsure which
// lever adjusts what, and therefore never pushing a set hard enough to matter.
// Every entry names the specific adjustment and the landmark to line it up
// against.
//
// Videos come in two parts. `videoUrl` is a curated tutorial where one was
// found whose title clearly matches the movement; `videoSearch` backs every
// exercise with a search that cannot 404. The UI shows both, because a dead
// link while she is standing at a machine is the failure worth designing out.
// The curated links could not be confirmed live from the build environment
// (YouTube is unreachable there), which is exactly why the fallback stays.

import type { Exercise } from './types';

/** Always-works fallback: a search never 404s the way a fixed video id does. */
export const ytSearch = (q: string) =>
  `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`;

/** True when a specific video has been picked for this movement. */
export const hasCuratedVideo = (ex: Exercise) => ex.videoUrl.trim() !== '';

/**
 * Where the Watch button points. Curated video if there is one, search if not.
 *
 * "Not curated yet" is spelled `videoUrl: ''` in this file, so this must be a
 * truthiness test — `ex.videoUrl ?? fallback` keeps the empty string and
 * renders href="", which is a link to nowhere that silently does nothing when
 * tapped. Both call sites go through here so they cannot disagree.
 */
export function demoUrl(ex: Exercise): string {
  return hasCuratedVideo(ex) ? ex.videoUrl : ytSearch(ex.videoSearch);
}

export const EXERCISES: Exercise[] = [
  // ------------------------------------------------------------------ lower
  {
    id: 'leg-extension',
    name: 'Leg extension',
    pattern: 'isolation',
    equipment: 'machine',
    primary: ['quads'],
    secondary: [],
    setup: [
      'Sit back so your hips are fully in the seat and your knee joint lines up with the round pivot point on the side of the machine.',
      'Slide the back pad forward or back until that line-up is right — this is the adjustment most people skip.',
      'Set the ankle pad so it sits on the front of your shin, just above the shoelaces. Not on the foot.',
      'Hold the side handles. Sit tall, do not lean back.',
    ],
    cues: [
      'Straighten your legs all the way and pause for a beat at the top.',
      'Lower under control — about twice as slow as you lifted.',
      'The whole set should be felt in the front of the thigh and nowhere else.',
    ],
    mistakes: [
      { wrong: 'Swinging the weight up with a hip thrust.', fix: 'Drop the weight until your back stays glued to the pad.' },
      { wrong: 'Stopping short of straight.', fix: 'Full lockout at the top is where the quad works hardest.' },
      { wrong: 'Pad sitting on the top of the foot.', fix: 'Move it down to the shin — on the foot it strains the ankle.' },
    ],
    videoUrl: 'https://www.youtube.com/watch?v=TJQmtXUEzNk',
    videoLabel: 'Leg extension — setup and form',
    videoSearch: 'leg extension machine proper form setup',
    ladder: ['leg-extension'],
    incrementKg: 5,
    bwRatio: 0.23,
    startKg: 15,
  },
  {
    id: 'leg-press',
    name: 'Leg press',
    pattern: 'squat',
    equipment: 'machine',
    // Quad-dominant unless the feet are set high. Glutes assist rather than lead —
    // counting them as primary here double-counts against the dedicated glute work.
    primary: ['quads'],
    secondary: ['glutes', 'hamstrings', 'adductors'],
    setup: [
      'Sit with your whole back and hips flat against the pad. No gap in your lower back.',
      'Feet on the platform about shoulder width, mid-foot height, toes turned slightly out.',
      'Higher feet loads the glutes and hamstrings more. Lower feet loads the quads more. Start in the middle.',
      'Push the platform up, then unlock the safety handles at the side. Keep a small bend in the knees at the top.',
    ],
    cues: [
      'Lower until your knees reach roughly 90 degrees, or as deep as you can go before your hips start curling off the pad.',
      'Push through the whole foot, especially the heel.',
      'Knees track over your toes — do not let them fall inward.',
    ],
    mistakes: [
      { wrong: 'Lowering so deep the lower back rounds off the pad.', fix: 'Stop where your hips stay planted. That is your depth for now.' },
      { wrong: 'Locking the knees hard at the top.', fix: 'Leave them slightly soft. Locking out puts the load on the joint, not the muscle.' },
      { wrong: 'Hands on the knees.', fix: 'Hold the side handles. Hands on knees hides how much your legs are actually doing.' },
    ],
    videoUrl: 'https://www.youtube.com/watch?v=8nm863C0c60',
    videoLabel: 'Leg press — setup, depth and foot placement',
    videoSearch: 'leg press machine proper form beginner',
    ladder: ['leg-press', 'goblet-squat', 'hack-squat', 'barbell-back-squat'],
    incrementKg: 5,
    bwRatio: 0.61,
    startKg: 40,
  },
  {
    id: 'goblet-squat',
    name: 'Goblet squat',
    pattern: 'squat',
    equipment: 'dumbbell',
    primary: ['quads', 'glutes'],
    secondary: ['core', 'upper-back'],
    setup: [
      'Hold one dumbbell vertically against your chest, cupping the top end with both hands.',
      'Feet a little wider than shoulder width, toes turned out about 20 degrees.',
      'Elbows tucked inside your knees, chest up.',
    ],
    cues: [
      'Sit straight down between your feet, not backwards.',
      'The dumbbell acts as a counterweight — it is what makes this easier to learn than a barbell.',
      'Drive up through the middle of the foot.',
    ],
    mistakes: [
      { wrong: 'Heels lifting off the floor.', fix: 'Widen the stance slightly, or stand with your heels on small plates while you build ankle range.' },
      { wrong: 'Knees caving inward.', fix: 'Think about pushing the floor apart with your feet.' },
    ],
    videoUrl: '',
    videoLabel: 'Goblet squat — the bridge to free-weight squatting',
    videoSearch: 'goblet squat form beginner',
    ladder: ['leg-press', 'goblet-squat', 'hack-squat', 'barbell-back-squat'],
    incrementKg: 2,
    bwRatio: 0.15,
    startKg: 10,
  },
  {
    id: 'hack-squat',
    name: 'Hack squat',
    pattern: 'squat',
    equipment: 'machine',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings'],
    setup: [
      'Back and shoulders firmly against the pads, feet mid-platform at shoulder width.',
      'Unlock the safeties, then descend with control.',
    ],
    cues: ['Knees travel forward over the toes — that is correct here.', 'Keep constant tension; do not rest at the top.'],
    mistakes: [{ wrong: 'Bouncing out of the bottom.', fix: 'Pause for a beat, then drive. Bouncing loads the knee, not the quad.' }],
    videoUrl: '',
    videoLabel: 'Hack squat — form',
    videoSearch: 'hack squat machine form',
    ladder: ['leg-press', 'goblet-squat', 'hack-squat', 'barbell-back-squat'],
    incrementKg: 5,
    bwRatio: 0.31,
    startKg: 20,
  },
  {
    id: 'barbell-back-squat',
    name: 'Barbell back squat',
    pattern: 'squat',
    equipment: 'barbell',
    primary: ['quads', 'glutes'],
    secondary: ['core', 'lower-back', 'hamstrings'],
    setup: [
      'Set the rack hooks at roughly mid-chest height, and the safety bars just below your lowest squat depth.',
      'Bar across the meat of the upper back, not on the bony bit at the base of the neck.',
      'Stand up, take two steps back, feet shoulder width.',
    ],
    cues: ['Big breath in, brace as if about to be poked in the stomach.', 'Sit down and slightly back.', 'Drive the whole foot into the floor.'],
    mistakes: [
      { wrong: 'Training without the safety bars set.', fix: 'Always set them. They are what makes failing a rep a non-event.' },
      { wrong: 'Chest dropping forward out of the bottom.', fix: 'Lighter load and hold the brace. Speed comes later.' },
    ],
    videoUrl: '',
    videoLabel: 'Back squat — rack setup and bracing',
    videoSearch: 'barbell back squat form beginner tutorial',
    ladder: ['leg-press', 'goblet-squat', 'hack-squat', 'barbell-back-squat'],
    incrementKg: 2.5,
    bwRatio: 0.31,
    startKg: 20,
  },
  {
    id: 'seated-leg-curl',
    name: 'Seated leg curl',
    pattern: 'isolation',
    equipment: 'machine',
    primary: ['hamstrings'],
    secondary: ['calves'],
    setup: [
      'Line your knee joint up with the machine pivot, same principle as the leg extension.',
      'Ankle pad across the back of your lower calf, just above the heel.',
      'Pull the lap pad down snug so your hips cannot lift.',
    ],
    cues: ['Curl your heels down and under the seat as far as they go.', 'Let the weight back up slowly — 3 seconds.'],
    mistakes: [
      { wrong: 'Hips lifting off the seat.', fix: 'Tighten the lap pad, drop the weight.' },
      { wrong: 'Half reps.', fix: 'Full range. The hamstring only gets strong where you train it.' },
    ],
    videoUrl: 'https://www.youtube.com/watch?v=t9sTSr-JYSs',
    videoLabel: 'Seated leg curl — setup',
    videoSearch: 'seated leg curl machine form',
    ladder: ['lying-leg-curl', 'seated-leg-curl'],
    incrementKg: 5,
    bwRatio: 0.23,
    startKg: 15,
  },
  {
    id: 'lying-leg-curl',
    name: 'Lying leg curl',
    pattern: 'isolation',
    equipment: 'machine',
    primary: ['hamstrings'],
    secondary: ['calves'],
    setup: [
      'Lie face down with your hips flat on the pad — if the bench has a bend in it, your hips go over the bend.',
      'Line your knee joint up with the machine pivot, just off the end of the pad.',
      'Ankle pad across the back of your lower calf, just above the heel.',
      'Hold the handles under the bench and keep your hips pressed down throughout.',
    ],
    cues: [
      'Curl your heels towards your backside as far as they will go.',
      'Lower slowly — about three seconds — and stop just short of your legs going fully straight.',
      'Point your toes towards your shins to keep the work in the hamstring rather than the calf.',
    ],
    mistakes: [
      { wrong: 'Hips lifting off the bench at the top.', fix: 'Press them down and use less weight. Lifting the hips is the hamstring handing the job to your lower back.' },
      { wrong: 'Half reps.', fix: 'Full range both ways. The hamstring only gets strong where you train it.' },
    ],
    videoUrl: '',
    videoLabel: 'Lying leg curl — setup and form',
    videoSearch: 'lying leg curl machine proper form hips down',
    ladder: ['lying-leg-curl', 'seated-leg-curl'],
    incrementKg: 5,
    bwRatio: 0.23,
    startKg: 15,
  },
  {
    id: 'hip-thrust-machine',
    name: 'Hip thrust (machine)',
    pattern: 'hinge',
    equipment: 'machine',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    setup: [
      'Sit with the pad across your hips, just below the bony points at the front.',
      'Back against the rest, feet flat and shoulder width, shins vertical at the top of the movement.',
      'If your shins angle forward, move your feet back. If your knees pass your toes, move them forward.',
    ],
    cues: [
      'Drive your hips up until your body makes a straight line from knee to shoulder.',
      'Squeeze hard at the top for a full second. That squeeze is the exercise.',
      'Tuck your chin slightly and keep your ribs down.',
    ],
    mistakes: [
      { wrong: 'Arching the lower back at the top instead of squeezing the glutes.', fix: 'Ribs down, chin tucked. The lift should stop when your body is straight, not past it.' },
      { wrong: 'Feet too far forward.', fix: 'Shins should be vertical at the top — that is the whole cue.' },
    ],
    videoUrl: 'https://www.youtube.com/watch?v=01rcKtWWvwE',
    videoLabel: 'Hip thrust — the single best glute exercise',
    videoSearch: 'hip thrust machine form glute',
    ladder: ['hip-thrust-machine', 'barbell-hip-thrust'],
    incrementKg: 5,
    bwRatio: 0.46,
    startKg: 30,
  },
  {
    id: 'barbell-hip-thrust',
    name: 'Barbell hip thrust',
    pattern: 'hinge',
    equipment: 'barbell',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    setup: [
      'Sit on the floor with your shoulder blades against the long edge of a bench.',
      'Roll the loaded bar over your legs until it sits in the crease of your hips. Use a thick pad.',
      'Feet flat, shins vertical at the top.',
    ],
    cues: ['Push through your heels, squeeze at the top, chin tucked.', 'Lower until the plates almost touch, then go again.'],
    mistakes: [{ wrong: 'Bar sitting on the thighs rather than the hip crease.', fix: 'Roll it further up. Wrong position means it never loads the glutes.' }],
    videoUrl: 'https://www.youtube.com/watch?v=6W-ViLupxKE',
    videoLabel: 'Barbell hip thrust — setup',
    videoSearch: 'barbell hip thrust setup form',
    ladder: ['hip-thrust-machine', 'barbell-hip-thrust'],
    incrementKg: 2.5,
    bwRatio: 0.46,
    startKg: 30,
  },
  {
    id: 'db-rdl',
    name: 'Dumbbell Romanian deadlift',
    pattern: 'hinge',
    equipment: 'dumbbell',
    primary: ['hamstrings', 'glutes'],
    secondary: ['lower-back', 'upper-back'],
    setup: [
      'A dumbbell in each hand, hanging in front of your thighs.',
      'Feet hip width, knees softly bent and then kept at that same bend the whole time.',
      'Shoulders pulled back, weights close to your legs.',
    ],
    cues: [
      'Push your hips backwards, as if reaching your backside to a wall behind you.',
      'The weights slide down your thighs. Stop when you feel a strong stretch behind the knees — usually just below the kneecap.',
      'Stand up by squeezing your glutes, not by pulling with your back.',
    ],
    mistakes: [
      { wrong: 'Turning it into a squat by bending the knees more as you go down.', fix: 'Fix the knee angle at the start. Only the hips move.' },
      { wrong: 'Rounding the lower back to reach further.', fix: 'Range is limited by your hamstrings, not your spine. Stop where the back stays flat.' },
      { wrong: 'Weights drifting away from the legs.', fix: 'Keep them brushing your thighs. Distance multiplies the load on your back.' },
    ],
    videoUrl: 'https://www.youtube.com/watch?v=3zqDris6lD4',
    videoLabel: 'Dumbbell RDL — the hip hinge',
    videoSearch: 'dumbbell romanian deadlift RDL form beginner',
    ladder: ['back-extension', 'db-rdl', 'barbell-rdl'],
    incrementKg: 2,
    bwRatio: 0.12,
    startKg: 8,
  },
  {
    id: 'barbell-rdl',
    name: 'Barbell Romanian deadlift',
    pattern: 'hinge',
    equipment: 'barbell',
    primary: ['hamstrings', 'glutes'],
    secondary: ['lower-back', 'upper-back', 'traps'],
    setup: ['Take the bar out of a rack at hip height rather than lifting it from the floor.', 'Hands just outside the hips, feet hip width.'],
    cues: ['Same hinge as the dumbbell version.', 'Bar stays in contact with your legs the whole way down.'],
    mistakes: [{ wrong: 'Bar drifting forward.', fix: 'Pull it back into your legs. Think of shaving your thighs with it.' }],
    videoUrl: '',
    videoLabel: 'Barbell RDL — form',
    videoSearch: 'barbell romanian deadlift form',
    ladder: ['back-extension', 'db-rdl', 'barbell-rdl'],
    incrementKg: 2.5,
    bwRatio: 0.31,
    startKg: 20,
  },
  {
    id: 'back-extension',
    name: '45-degree back extension',
    pattern: 'hinge',
    equipment: 'bodyweight',
    primary: ['glutes', 'hamstrings'],
    secondary: ['lower-back'],
    setup: [
      'Set the pad so its top edge sits just below your hip bones — low enough that your hips can bend freely.',
      'Ankles secured, feet turned slightly out to bias the glutes.',
      'Arms crossed over your chest.',
    ],
    cues: ['Round your upper back slightly and tuck your chin — this is a glute exercise, not a lower-back one.', 'Rise until your body is straight, then stop. Do not go past straight.'],
    mistakes: [
      { wrong: 'Hyperextending at the top.', fix: 'Stop at straight. Past that, all the load lands on the lower back.' },
      { wrong: 'Pad set too high.', fix: 'Drop it below the hip bones or your hips cannot hinge.' },
    ],
    videoUrl: '',
    videoLabel: 'Back extension — glute-biased setup',
    videoSearch: '45 degree back extension glute form',
    ladder: ['back-extension', 'db-rdl', 'barbell-rdl'],
    incrementKg: 2.5,
    bwRatio: 0,
    startKg: 0,
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian split squat',
    pattern: 'lunge',
    equipment: 'dumbbell',
    primary: ['quads', 'glutes'],
    secondary: ['adductors', 'core'],
    setup: [
      'Stand about one long stride in front of a bench, back foot resting on it, laces down.',
      'Too close and your knee gets crowded. Too far and you cannot reach depth. Adjust until the front shin is roughly vertical at the bottom.',
      'Start with no weight until the balance feels solid.',
    ],
    cues: ['Drop straight down, front heel planted.', 'Leaning the torso forward slightly shifts the work to the glute.'],
    mistakes: [
      { wrong: 'Front foot too close to the bench.', fix: 'Step it further forward. Your front knee should not be shoved past your toes.' },
      { wrong: 'Adding weight before balance is there.', fix: 'Hold a rack upright with one hand for the first few sessions.' },
    ],
    videoUrl: '',
    videoLabel: 'Bulgarian split squat — foot placement',
    videoSearch: 'bulgarian split squat form beginner',
    ladder: ['bulgarian-split-squat'],
    incrementKg: 2,
    bwRatio: 0,
    startKg: 0,
  },
  {
    id: 'hip-abduction',
    name: 'Seated hip abduction',
    pattern: 'isolation',
    equipment: 'machine',
    // Hits the upper/outer glute rather than the glute max the hip thrust trains.
    primary: ['abductors'],
    secondary: ['glutes'],
    setup: ['Sit tall with the pads against the outside of your knees.', 'Leaning the torso forward slightly biases the upper glute.'],
    cues: ['Push your knees apart, hold for a beat at the widest point, return slowly.'],
    mistakes: [{ wrong: 'Slamming the pads out and letting them snap back.', fix: 'Control both directions. The return is half the work.' }],
    videoUrl: '',
    videoLabel: 'Hip abduction — form',
    videoSearch: 'hip abduction machine glute medius form',
    ladder: ['hip-abduction'],
    incrementKg: 5,
    bwRatio: 0.31,
    startKg: 20,
  },
  {
    id: 'standing-calf-raise',
    name: 'Standing calf raise',
    pattern: 'isolation',
    equipment: 'machine',
    primary: ['calves'],
    secondary: [],
    setup: ['Balls of the feet on the edge of the platform, heels hanging free.', 'Shoulder pads snug, legs straight but knees not locked.'],
    cues: ['Drop the heels as low as they will go for a full stretch, then rise all the way onto the toes.', 'Pause a second at both ends.'],
    mistakes: [{ wrong: 'Fast, bouncy half reps.', fix: 'Slow down and use the full range. Calves respond to stretch, not bounce.' }],
    videoUrl: '',
    videoLabel: 'Calf raise — full range',
    videoSearch: 'standing calf raise machine form',
    ladder: ['standing-calf-raise'],
    incrementKg: 5,
    bwRatio: 0.31,
    startKg: 20,
  },

  // ------------------------------------------------------------------ upper
  {
    id: 'chest-press-machine',
    name: 'Chest press (machine)',
    pattern: 'push-h',
    equipment: 'machine',
    primary: ['chest'],
    secondary: ['front-delts', 'triceps'],
    setup: [
      'Adjust the seat height so the handles sit level with the middle of your chest, roughly at nipple height.',
      'Too high and it becomes a shoulder exercise. This is the adjustment that matters.',
      'Back flat against the pad, feet flat on the floor.',
    ],
    cues: ['Press forward and slightly together.', 'Stop just short of locking the elbows.', 'Let the handles come back until you feel a stretch across the chest.'],
    mistakes: [
      { wrong: 'Seat too low, pressing upward.', fix: 'Raise it. The handles should line up with mid-chest.' },
      { wrong: 'Shoulders rolling forward at the end of the press.', fix: 'Keep the shoulder blades pinned back against the pad throughout.' },
    ],
    videoUrl: '',
    videoLabel: 'Machine chest press — seat height',
    videoSearch: 'chest press machine seat height form',
    ladder: ['chest-press-machine', 'db-bench-press', 'barbell-bench-press'],
    incrementKg: 5,
    bwRatio: 0.23,
    startKg: 15,
  },
  {
    id: 'db-bench-press',
    name: 'Dumbbell bench press',
    pattern: 'push-h',
    equipment: 'dumbbell',
    primary: ['chest'],
    secondary: ['front-delts', 'triceps'],
    setup: [
      'Sit on the end of the bench with the dumbbells on your thighs, then kick them back one at a time as you lie down.',
      'Shoulder blades pinched together and pulled down.',
      'Feet flat on the floor.',
    ],
    cues: ['Elbows about 45 degrees from your body, not flared straight out.', 'Lower until your upper arms are level with the bench.'],
    mistakes: [
      { wrong: 'Elbows flared to 90 degrees.', fix: 'Tuck them to 45. Flaring is the most common way to end up with a sore shoulder.' },
      { wrong: 'Dropping the dumbbells at the end of the set.', fix: 'Sit up with them, then set them down. Practise with light weights.' },
    ],
    videoUrl: '',
    videoLabel: 'DB bench press — getting into position',
    videoSearch: 'dumbbell bench press form beginner setup',
    ladder: ['chest-press-machine', 'db-bench-press', 'barbell-bench-press'],
    incrementKg: 2,
    bwRatio: 0.12,
    startKg: 8,
  },
  {
    id: 'barbell-bench-press',
    name: 'Barbell bench press',
    pattern: 'push-h',
    equipment: 'barbell',
    primary: ['chest'],
    secondary: ['front-delts', 'triceps'],
    setup: ['Eyes under the bar, shoulder blades pinched, feet flat.', 'Set the safety bars at chest height whenever you train alone.'],
    cues: ['Lower to the lower chest, elbows tucked to 45 degrees.', 'Touch, then press back over the shoulders.'],
    mistakes: [{ wrong: 'Benching alone without safeties.', fix: 'Set them every time. It is the difference between a failed rep and a real problem.' }],
    videoUrl: '',
    videoLabel: 'Barbell bench — setup and safeties',
    videoSearch: 'barbell bench press form beginner',
    ladder: ['chest-press-machine', 'db-bench-press', 'barbell-bench-press'],
    incrementKg: 2.5,
    bwRatio: 0.31,
    startKg: 20,
  },
  {
    id: 'machine-shoulder-press',
    name: 'Shoulder press (machine)',
    pattern: 'push-v',
    equipment: 'machine',
    primary: ['front-delts'],
    secondary: ['side-delts', 'triceps'],
    setup: ['Seat height so the handles start at about ear or shoulder height.', 'Back flat against the pad, core braced.'],
    cues: ['Press up and slightly in.', 'Stop just short of lockout, lower under control to ear height.'],
    mistakes: [{ wrong: 'Arching the lower back to help.', fix: 'Brace, and lower the weight. An arch turns it into a bad incline press.' }],
    videoUrl: '',
    videoLabel: 'Machine shoulder press — form',
    videoSearch: 'machine shoulder press form',
    ladder: ['machine-shoulder-press', 'seated-db-press', 'standing-barbell-press'],
    incrementKg: 5,
    bwRatio: 0.15,
    startKg: 10,
  },
  {
    id: 'seated-db-press',
    name: 'Seated dumbbell shoulder press',
    pattern: 'push-v',
    equipment: 'dumbbell',
    primary: ['front-delts'],
    secondary: ['side-delts', 'triceps', 'core'],
    setup: ['Upright bench, back supported, dumbbells at ear height with palms forward.'],
    cues: ['Press up until the dumbbells nearly touch.', 'Ribs down, do not let the back arch.'],
    mistakes: [{ wrong: 'Starting too low.', fix: 'Ear height is the start. Deeper puts the shoulder joint in a bad spot under load.' }],
    videoUrl: '',
    videoLabel: 'Seated DB press — form',
    videoSearch: 'seated dumbbell shoulder press form',
    ladder: ['machine-shoulder-press', 'seated-db-press', 'standing-barbell-press'],
    incrementKg: 2,
    bwRatio: 0.09,
    startKg: 6,
  },
  {
    id: 'standing-barbell-press',
    name: 'Standing barbell press',
    pattern: 'push-v',
    equipment: 'barbell',
    primary: ['front-delts'],
    secondary: ['triceps', 'core', 'upper-back'],
    setup: ['Bar on the front shoulders, hands just outside shoulder width, elbows slightly in front of the bar.'],
    cues: ['Squeeze the glutes and brace hard — this is a full-body lift.', 'Move your head back slightly to let the bar pass, then push it overhead.'],
    mistakes: [{ wrong: 'Leaning back to press.', fix: 'Brace the core and squeeze the glutes. The body stays a rigid column.' }],
    videoUrl: '',
    videoLabel: 'Overhead press — bracing',
    videoSearch: 'standing barbell overhead press form beginner',
    ladder: ['machine-shoulder-press', 'seated-db-press', 'standing-barbell-press'],
    incrementKg: 2.5,
    bwRatio: 0.23,
    startKg: 15,
  },
  {
    id: 'lat-pulldown',
    name: 'Lat pulldown',
    pattern: 'pull-v',
    equipment: 'machine',
    primary: ['lats'],
    secondary: ['upper-back', 'biceps', 'rear-delts'],
    setup: [
      'Set the thigh pad down tight enough that you cannot lift off the seat.',
      'Grip slightly wider than shoulder width, palms forward.',
      'Sit tall and lean back about 15 degrees. Hold that lean the whole set.',
    ],
    cues: [
      'Start by pulling your shoulders down away from your ears, then pull the bar to your upper chest.',
      'Think about driving your elbows down into your back pockets rather than pulling with your hands.',
      'Let the bar go all the way up until you feel the stretch, without your shoulders shrugging up.',
    ],
    mistakes: [
      { wrong: 'Rocking backwards to move the weight.', fix: 'Fix the lean at the start and hold it. Only the arms move.' },
      { wrong: 'Pulling the bar behind the neck.', fix: 'To the front, at the upper chest. Behind the neck is unnecessary and hard on the shoulder.' },
      { wrong: 'Feeling it all in the biceps.', fix: 'Lead with the elbows and start each rep with the shoulder blade, not the hand.' },
    ],
    videoUrl: 'https://www.youtube.com/watch?v=AOpi-p0cJkc',
    videoLabel: 'Lat pulldown — leading with the elbows',
    videoSearch: 'lat pulldown proper form beginner mind muscle',
    ladder: ['lat-pulldown', 'assisted-pull-up', 'pull-up'],
    incrementKg: 5,
    bwRatio: 0.31,
    startKg: 20,
  },
  {
    id: 'assisted-pull-up',
    name: 'Assisted pull-up',
    pattern: 'pull-v',
    equipment: 'machine',
    primary: ['lats'],
    secondary: ['upper-back', 'biceps', 'core'],
    setup: ['Kneel or stand on the pad. More assistance weight makes it easier — this stack works backwards from every other machine.', 'Grip slightly wider than shoulders.'],
    cues: ['Shoulders down first, then pull until your chin clears the bar.', 'Lower all the way under control.'],
    mistakes: [{ wrong: 'Reducing assistance too fast.', fix: 'Drop it 5 kg at a time, and only once you can do all your sets at the top of the rep range.' }],
    videoUrl: '',
    videoLabel: 'Assisted pull-up — progressing off the machine',
    videoSearch: 'assisted pull up machine form progression',
    ladder: ['lat-pulldown', 'assisted-pull-up', 'pull-up'],
    incrementKg: 5,
    bwRatio: 0.54,
    startKg: 35,
  },
  {
    id: 'pull-up',
    name: 'Pull-up',
    pattern: 'pull-v',
    equipment: 'bodyweight',
    primary: ['lats'],
    secondary: ['upper-back', 'biceps', 'core'],
    setup: ['Hands slightly wider than shoulders, palms forward, hanging with arms straight.'],
    cues: ['Pull the shoulder blades down first, then drive the elbows to your ribs.', 'Chin over the bar, then lower all the way.'],
    mistakes: [{ wrong: 'Half reps from a bent-arm start.', fix: 'Full hang every rep. Fewer good ones beat more partial ones.' }],
    videoUrl: '',
    videoLabel: 'Pull-up — the progression',
    videoSearch: 'first pull up progression women',
    ladder: ['lat-pulldown', 'assisted-pull-up', 'pull-up'],
    incrementKg: 2.5,
    bwRatio: 0,
    startKg: 0,
  },
  {
    id: 'seated-cable-row',
    name: 'Seated cable row',
    pattern: 'pull-h',
    equipment: 'cable',
    primary: ['upper-back', 'lats'],
    secondary: ['biceps', 'rear-delts'],
    setup: ['Feet on the platform, knees softly bent.', 'Sit tall with a small forward lean at the start of each rep, chest up.'],
    cues: ['Pull the handle to your belly button, driving the elbows past your ribs.', 'Squeeze the shoulder blades together for a beat, then let the arms extend fully.'],
    mistakes: [
      { wrong: 'Rowing with the whole torso swinging back and forth.', fix: 'The torso stays almost still. If it is swinging, the weight is too heavy.' },
      { wrong: 'Shrugging at the top.', fix: 'Pull back and down, not up.' },
    ],
    videoUrl: 'https://www.youtube.com/watch?v=EU7bOadUsNI',
    videoLabel: 'Cable row — squeezing the shoulder blades',
    videoSearch: 'seated cable row proper form back',
    ladder: ['seated-cable-row', 'chest-supported-row', 'barbell-row'],
    incrementKg: 5,
    bwRatio: 0.31,
    startKg: 20,
  },
  {
    id: 'chest-supported-row',
    name: 'Chest-supported dumbbell row',
    pattern: 'pull-h',
    equipment: 'dumbbell',
    primary: ['upper-back', 'lats'],
    secondary: ['biceps', 'rear-delts'],
    setup: ['Set an incline bench to about 45 degrees and lie face down on it, chest supported.', 'Dumbbells hanging straight down.'],
    cues: ['Row the dumbbells towards your hips, elbows close to the body.', 'Squeeze at the top, lower slowly.'],
    mistakes: [{ wrong: 'Lifting the chest off the bench to help.', fix: 'Chest stays down. The support is the point — it stops your lower back cheating.' }],
    videoUrl: '',
    videoLabel: 'Chest-supported row — form',
    videoSearch: 'chest supported dumbbell row incline bench form',
    ladder: ['seated-cable-row', 'chest-supported-row', 'barbell-row'],
    incrementKg: 2,
    bwRatio: 0.11,
    startKg: 7,
  },
  {
    id: 'barbell-row',
    name: 'Barbell row',
    pattern: 'pull-h',
    equipment: 'barbell',
    primary: ['upper-back', 'lats'],
    secondary: ['lower-back', 'biceps', 'rear-delts'],
    setup: ['Hinge forward to about 45 degrees with a flat back, bar hanging at arms length.'],
    cues: ['Row to the belly button, elbows tucked.', 'Hold the torso angle still for the whole set.'],
    mistakes: [{ wrong: 'Standing up as the set gets hard.', fix: 'Lower the weight. The angle holding still is what makes it a row.' }],
    videoUrl: '',
    videoLabel: 'Barbell row — form',
    videoSearch: 'barbell row form beginner',
    ladder: ['seated-cable-row', 'chest-supported-row', 'barbell-row'],
    incrementKg: 2.5,
    bwRatio: 0.31,
    startKg: 20,
  },
  {
    id: 'incline-db-press',
    name: 'Incline dumbbell press',
    pattern: 'push-h',
    equipment: 'dumbbell',
    primary: ['chest', 'front-delts'],
    secondary: ['triceps'],
    setup: ['Bench at 30 degrees — higher than that and it becomes a shoulder press.', 'Shoulder blades pinned back, dumbbells at chest height.'],
    cues: ['Press up and slightly together.', 'Lower until you feel a stretch across the upper chest.'],
    mistakes: [{ wrong: 'Bench set too steep.', fix: '30 degrees. Most benches have a notch marked for it.' }],
    videoUrl: '',
    videoLabel: 'Incline DB press — bench angle',
    videoSearch: 'incline dumbbell press 30 degrees form',
    ladder: ['incline-db-press'],
    incrementKg: 2,
    bwRatio: 0.09,
    startKg: 6,
  },
  {
    id: 'cable-lateral-raise',
    name: 'Cable lateral raise',
    pattern: 'isolation',
    equipment: 'cable',
    primary: ['side-delts'],
    secondary: [],
    setup: [
      'Pulley set to the lowest position, standing side-on with the cable crossing in front of your body.',
      'Grab the handle with the hand furthest from the machine.',
    ],
    cues: [
      'Raise your arm out to the side up to shoulder height, no higher.',
      'Lead with the elbow, not the hand — as if pouring from a jug.',
      'Lower slowly. The cable keeps tension at the bottom, which a dumbbell does not.',
    ],
    mistakes: [
      { wrong: 'Going far too heavy and swinging.', fix: 'This is a small muscle. 2.5 to 5 kg is a real working weight, and that is fine.' },
      { wrong: 'Shrugging the shoulder up.', fix: 'Keep the shoulder pressed down. If it rises, the traps have taken over.' },
    ],
    videoUrl: '',
    videoLabel: 'Cable lateral raise — shoulder width',
    videoSearch: 'cable lateral raise side delt form',
    ladder: ['db-lateral-raise', 'cable-lateral-raise'],
    incrementKg: 2.5,
    bwRatio: 0.038,
    startKg: 2.5,
  },
  {
    id: 'db-lateral-raise',
    name: 'Dumbbell lateral raise',
    pattern: 'isolation',
    equipment: 'dumbbell',
    primary: ['side-delts'],
    secondary: ['traps'],
    setup: [
      'A light dumbbell in each hand, standing tall, arms at your sides.',
      'Start lighter than you think. 3 to 5 kg is a real working weight here.',
    ],
    cues: [
      'Raise both arms out to the side to shoulder height, no higher.',
      'Lead with the elbows, as if pouring from a jug, with a slight bend in the arm.',
      'Lower slowly — the way down is where most of the work is with dumbbells.',
    ],
    mistakes: [
      { wrong: 'Swinging the weights up with a bounce from the knees.', fix: 'Go lighter. If your body moves, the shoulders are not doing it.' },
      { wrong: 'Raising above shoulder height.', fix: 'Stop level with your shoulders. Past that the traps take over.' },
    ],
    videoUrl: '',
    videoLabel: 'DB lateral raise — the width builder',
    videoSearch: 'dumbbell lateral raise form side delt',
    // Dumbbells are simpler to get hold of; the cable is the progression, because
    // it keeps tension on the muscle at the bottom where a dumbbell goes slack.
    ladder: ['db-lateral-raise', 'cable-lateral-raise'],
    incrementKg: 2,
    bwRatio: 0.06,
    startKg: 4,
  },
  {
    id: 'face-pull',
    name: 'Face pull',
    pattern: 'isolation',
    equipment: 'cable',
    primary: ['rear-delts', 'upper-back'],
    secondary: ['traps'],
    setup: ['Rope attachment set at roughly face height.', 'Step back until there is tension with your arms straight.'],
    cues: ['Pull the rope towards your forehead, splitting your hands apart as you go.', 'Finish with your knuckles beside your ears and elbows high.'],
    mistakes: [{ wrong: 'Pulling it to the chest like a row.', fix: 'Elbows high, hands to the ears. Higher than feels natural.' }],
    videoUrl: 'https://www.youtube.com/watch?v=3pToT5_DUiY',
    videoLabel: 'Face pull — posture insurance',
    videoSearch: 'face pull rope form rear delt',
    ladder: ['face-pull'],
    incrementKg: 2.5,
    bwRatio: 0.15,
    startKg: 10,
  },
  {
    id: 'triceps-pushdown',
    name: 'Triceps pushdown',
    pattern: 'isolation',
    equipment: 'cable',
    primary: ['triceps'],
    secondary: [],
    setup: ['Rope or bar at the top pulley.', 'Stand close, elbows pinned to your sides, small forward lean.'],
    cues: ['Only the forearms move. Straighten fully and squeeze.', 'Let the weight come up until your forearms are past parallel.'],
    mistakes: [{ wrong: 'Elbows drifting forward and away from the body.', fix: 'Pin them to your ribs. If they move, the back and chest are helping.' }],
    videoUrl: '',
    videoLabel: 'Pushdown — elbow position',
    videoSearch: 'triceps pushdown cable form',
    ladder: ['triceps-pushdown'],
    incrementKg: 2.5,
    bwRatio: 0.15,
    startKg: 10,
  },
  {
    id: 'cable-curl',
    name: 'Cable biceps curl',
    pattern: 'isolation',
    equipment: 'cable',
    primary: ['biceps'],
    secondary: [],
    setup: ['Bar at the low pulley, elbows at your sides, standing tall.'],
    cues: ['Curl up without letting the elbows travel forward.', 'Lower slowly all the way to straight.'],
    mistakes: [{ wrong: 'Swinging the body to start each rep.', fix: 'Stand against a wall or drop the weight.' }],
    videoUrl: '',
    videoLabel: 'Cable curl — form',
    videoSearch: 'cable biceps curl form',
    ladder: ['db-curl', 'cable-curl'],
    incrementKg: 2.5,
    bwRatio: 0.115,
    startKg: 7.5,
  },

  {
    id: 'standing-cable-abduction',
    name: 'Standing hip abduction (cable)',
    pattern: 'isolation',
    equipment: 'cable',
    primary: ['abductors'],
    secondary: ['glutes', 'core'],
    setup: [
      'Ankle strap on the low pulley, fastened to the leg furthest from the machine.',
      'Stand side-on, holding the frame for balance. Step away until there is tension with your legs together.',
      'Stand tall — the working leg moves, nothing else does.',
    ],
    cues: [
      'Lift the strapped leg out to the side, keeping it straight and your toes pointing forward.',
      'Stop when your hip starts to hitch upward, then lower slowly against the cable.',
    ],
    mistakes: [
      { wrong: 'Leaning away to get the leg higher.', fix: 'Height is not the point. Stay upright and go only as far as the hip allows.' },
      { wrong: 'Turning the toes out.', fix: 'Toes forward keeps it on the side of the glute rather than the front of the hip.' },
    ],
    videoUrl: '',
    videoLabel: 'Standing cable abduction — form',
    videoSearch: 'standing cable hip abduction form glute medius',
    ladder: ['standing-cable-abduction'],
    incrementKg: 2.5,
    bwRatio: 0.09,
    startKg: 5,
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated calf raise',
    pattern: 'isolation',
    equipment: 'machine',
    primary: ['calves'],
    secondary: [],
    setup: [
      'Sit with the balls of your feet on the platform and the pads snug across your lower thighs, just above the knee.',
      'Release the safety lever before you start.',
    ],
    cues: [
      'Drop the heels as far as they will go, then push all the way up onto the toes.',
      'Bent knees shift the work to the deeper calf muscle — this is the useful partner to the standing version, not a copy of it.',
    ],
    mistakes: [
      { wrong: 'Short, bouncy reps.', fix: 'Full range, pause at both ends. Calves respond to stretch, not bounce.' },
      { wrong: 'Pad sitting on the kneecap.', fix: 'Move it back onto the thigh — on the kneecap it is just painful.' },
    ],
    videoUrl: '',
    videoLabel: 'Seated calf raise — form',
    videoSearch: 'seated calf raise machine proper form',
    ladder: ['seated-calf-raise'],
    incrementKg: 5,
    bwRatio: 0.23,
    startKg: 15,
  },
  {
    id: 'single-leg-calf-raise',
    name: 'Single-leg calf raise',
    pattern: 'isolation',
    equipment: 'bodyweight',
    primary: ['calves'],
    secondary: ['core'],
    setup: [
      'Stand on one foot with the ball of the foot on a step or a weight plate, heel hanging off.',
      'Hold something for balance — this is a calf exercise, not a balance test.',
    ],
    cues: ['Lower the heel for a deep stretch, then push all the way up.', 'Slow on the way down.'],
    mistakes: [{ wrong: 'Bouncing off the bottom.', fix: 'Pause at the stretch for a second before you push.' }],
    videoUrl: '',
    videoLabel: 'Single-leg calf raise — form',
    videoSearch: 'single leg calf raise form',
    ladder: ['single-leg-calf-raise'],
    incrementKg: 0,
    bwRatio: 0,
    startKg: 0,
  },
  {
    id: 'overhead-triceps-extension',
    name: 'Overhead triceps extension',
    pattern: 'isolation',
    equipment: 'cable',
    primary: ['triceps'],
    secondary: ['core'],
    setup: [
      'Rope on the low or mid pulley. Face away from the machine, rope held behind your head, elbows pointing forward.',
      'Stagger your feet — one slightly in front — so you are not pulled backwards.',
    ],
    cues: [
      'Straighten your arms overhead, keeping the elbows pointing forward and close together.',
      'Let the rope come back down behind your head until you feel a stretch down the back of the arm.',
    ],
    mistakes: [
      { wrong: 'Elbows flaring out to the sides.', fix: 'Keep them pointing forward. Flaring turns it into a shoulder movement.' },
      { wrong: 'Whole body rocking.', fix: 'Stagger the stance and drop the weight. Only the forearms move.' },
    ],
    videoUrl: '',
    videoLabel: 'Overhead triceps extension — form',
    videoSearch: 'cable overhead triceps extension rope form',
    ladder: ['overhead-triceps-extension'],
    incrementKg: 2.5,
    bwRatio: 0.11,
    startKg: 7.5,
  },
  {
    id: 'db-curl',
    name: 'Dumbbell biceps curl',
    pattern: 'isolation',
    equipment: 'dumbbell',
    primary: ['biceps'],
    secondary: [],
    setup: [
      'A dumbbell in each hand, standing tall, arms hanging at your sides, palms facing forward.',
      'Elbows tucked against your ribs and staying there.',
    ],
    cues: [
      'Curl both up together without letting the elbows drift forward.',
      'Lower all the way to straight — the bottom half is where most people quietly cheat.',
    ],
    mistakes: [
      { wrong: 'Swinging the weights up with the back.', fix: 'Stand against a wall. If your shoulders touch it the whole set, you are being honest.' },
      { wrong: 'Stopping halfway down.', fix: 'Full extension every rep, even if it means less weight.' },
    ],
    videoUrl: '',
    videoLabel: 'Dumbbell curl — form',
    videoSearch: 'dumbbell biceps curl proper form',
    ladder: ['db-curl', 'cable-curl'],
    incrementKg: 2,
    bwRatio: 0.08,
    startKg: 5,
  },
  // ------------------------------------------------------------------- core
  {
    id: 'plank',
    name: 'Plank',
    pattern: 'core',
    equipment: 'bodyweight',
    primary: ['core'],
    secondary: ['glutes'],
    setup: ['Forearms on the floor under your shoulders, feet hip width.'],
    cues: ['Squeeze the glutes and tuck the hips slightly so the lower back flattens.', 'A hard 20 seconds beats a sagging two minutes.'],
    mistakes: [{ wrong: 'Hips sagging towards the floor.', fix: 'Tuck the hips and squeeze the glutes. Stop the set when the sag starts.' }],
    videoUrl: '',
    videoLabel: 'Plank — bracing properly',
    videoSearch: 'plank proper form hollow',
    ladder: ['plank'],
    incrementKg: 0,
    bwRatio: 0,
    startKg: 0,
  },
  {
    id: 'dead-bug',
    name: 'Dead bug',
    pattern: 'core',
    equipment: 'bodyweight',
    primary: ['core'],
    secondary: [],
    setup: ['On your back, arms straight up, knees bent at 90 degrees above the hips.'],
    cues: ['Press the lower back flat into the floor and keep it there.', 'Lower one arm and the opposite leg slowly, then swap.'],
    mistakes: [{ wrong: 'Lower back arching off the floor.', fix: 'Reduce the range. Only go as far as you can hold the back flat.' }],
    videoUrl: '',
    videoLabel: 'Dead bug — form',
    videoSearch: 'dead bug exercise form core',
    ladder: ['dead-bug'],
    incrementKg: 0,
    bwRatio: 0,
    startKg: 0,
  },
  {
    id: 'cable-woodchop',
    name: 'Half-kneeling cable chop',
    pattern: 'core',
    equipment: 'cable',
    primary: ['core'],
    secondary: ['side-delts'],
    setup: ['Pulley at shoulder height, kneel side-on with the inside knee up.'],
    cues: ['Rotate from the ribcage, hips stay square and still.', 'Slow and controlled both ways.'],
    mistakes: [{ wrong: 'Turning the hips with the torso.', fix: 'Lock the hips. The rotation is the exercise.' }],
    videoUrl: '',
    videoLabel: 'Cable chop — anti-rotation',
    videoSearch: 'half kneeling cable chop core form',
    ladder: ['cable-woodchop'],
    incrementKg: 2.5,
    bwRatio: 0.115,
    startKg: 7.5,
  },
];

const BY_ID = new Map(EXERCISES.map((e) => [e.id, e]));

export function getExercise(id: string): Exercise {
  const e = BY_ID.get(id);
  if (!e) throw new Error(`Unknown exercise: ${id}`);
  return e;
}

export function findExercise(id: string): Exercise | undefined {
  return BY_ID.get(id);
}

export const MUSCLE_LABELS: Record<string, string> = {
  glutes: 'Glutes',
  quads: 'Quads',
  hamstrings: 'Hamstrings',
  calves: 'Calves',
  adductors: 'Inner thigh',
  abductors: 'Outer glute',
  lats: 'Lats',
  'upper-back': 'Upper back',
  'lower-back': 'Lower back',
  traps: 'Traps',
  chest: 'Chest',
  'front-delts': 'Front shoulder',
  'side-delts': 'Side shoulder',
  'rear-delts': 'Rear shoulder',
  biceps: 'Biceps',
  triceps: 'Triceps',
  core: 'Core',
};

export const EQUIPMENT_LABELS: Record<string, string> = {
  machine: 'Machine',
  cable: 'Cable',
  dumbbell: 'Dumbbell',
  barbell: 'Barbell',
  bodyweight: 'Bodyweight',
};
